name: Pack

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Pack
        run: dotnet pack -c Release -o ./artifacts
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: ./artifacts
